name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "ReleaseBuild"
    runs-on: "ubuntu-latest"

    permissions:
      # required for all workflows
      security-events: read
      actions: write
      contents: write

    env:
      TAG: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: bruttazz
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bruttazz/apod-api:${{ env.TAG }}
          platforms: linux/amd64,linux/arm64

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --title="$tag" \
              --generate-notes
