name: Smoke Test

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "smokeTest"
  cancel-in-progress: true

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Smoke Test
        run: make test
